### ISSUE TITLE
New BackOfficePath is not fully considered

### ISSUE THREAD

**Issue by gmichard** [thelia-modules/BackOfficePath#1]
These URL should return a **404 Front** :
- `monsite..com/admin` : default path without trailing slash
- `monsite..com/admin/` : default path with trailing slash
- `monsite..com/abcdef/` : any path
- `monsite..com/abcdefadminabcdef/` : any path containing the old or new path
- `monsite..com/adminabcdef/` : ... prefixed
- `monsite..com/abcdefadmin/` : ... or sufffixed

Visitor unlogged, these URL should return the **BackOffice login page** :
- `monsite..com/newpath` : new path without trailing slash
- `monsite..com/newpath/` : new path with trailing slash
- `monsite..com/newpath/login`
- `monsite..com/newpath/login/`

**Comment by Soldras** [comment]
# Since v0.2

## These URL should return a 404 Front :
- monsite..com/admin : return 404 but bugged
- monsite..com/admin/ : return 404 but bugged
- monsite..com/abcdef/ : OK
- monsite..com/abcdefadminabcdef/ : OK
- monsite..com/adminabcdef/ : OK
- monsite..com/abcdefadmin/ : OK

## Visitor unlogged, these URL should return the BackOffice login page :
- monsite..com/newpath : OK
- monsite..com/newpath/ : OK
- monsite..com/newpath/login : OK
- monsite..com/newpath/login/ : OK

**Comment by gmichard** [comment]
Solved by #5.
